import type { Transaction } from './types';

export const transactions: Transaction[] = [
  {
    id: 'txn_1',
    userId: 'user_123',
    amount: 2500,
    type: 'income',
    category: 'Client Project A',
    date: '2024-07-01T10:00:00Z',
    paymentMethod: 'Bank Transfer',
    description: 'Payment for project A completion',
  },
  {
    id: 'txn_2',
    userId: 'user_123',
    amount: 120.5,
    type: 'expense',
    category: 'Software',
    date: '2024-07-02T14:30:00Z',
    paymentMethod: 'Credit Card',
    description: 'Figma Subscription',
  },
  {
    id: 'txn_3',
    userId: 'user_123',
    amount: 75.0,
    type: 'expense',
    category: 'Office Supplies',
    date: '2024-07-03T11:00:00Z',
    paymentMethod: 'Debit Card',
    description: 'Pens, paper, and notebooks',
  },
  {
    id: 'txn_4',
    userId: 'user_123',
    amount: 5000,
    type: 'income',
    category: 'Client Project B',
    date: '2024-07-05T16:00:00Z',
    paymentMethod: 'Stripe',
    description: 'Milestone 1 for Project B',
  },
  {
    id: 'txn_5',
    userId: 'user_123',
    amount: 350.0,
    type: 'expense',
    category: 'Marketing',
    date: '2024-07-08T09:00:00Z',
    paymentMethod: 'Credit Card',
    description: 'Google Ads Campaign',
  },
  {
    id: 'txn_6',
    userId: 'user_123',
    amount: 800.0,
    type: 'expense',
    category: 'Contractors',
    date: '2024-07-10T18:00:00Z',
    paymentMethod: 'PayPal',
    description: 'Freelance designer payment',
  },
  {
    id: 'txn_7',
    userId: 'user_123',
    amount: 45.99,
    type: 'expense',
    category: 'Utilities',
    date: '2024-07-12T12:00:00Z',
    paymentMethod: 'Auto-debit',
    description: 'Internet Bill',
  },
  {
    id: 'txn_8',
    userId: 'user_123',
    amount: 1500,
    type: 'income',
    category: 'Consulting',
    date: '2024-07-15T10:30:00Z',
    paymentMethod: 'Bank Transfer',
    description: 'Hourly consulting services',
  },
  {
    id: 'txn_9',
    userId: 'user_123',
    amount: 250,
    type: 'expense',
    category: 'Travel',
    date: '2024-07-18T20:00:00Z',
    paymentMethod: 'Credit Card',
    description: 'Train ticket for client meeting',
  },
  {
    id: 'txn_10',
    userId: 'user_123',
    amount: 120.5,
    type: 'expense',
    category: 'Software',
    date: '2024-07-20T14:35:00Z',
    paymentMethod: 'Credit Card',
    description: 'Adobe Creative Cloud',
  },
  {
    id: 'txn_11',
    userId: 'user_123',
    amount: 3200,
    type: 'income',
    category: 'Client Project C',
    date: '2024-06-25T10:00:00Z',
    paymentMethod: 'Bank Transfer',
    description: 'Upfront payment for project C',
  },
  {
    id: 'txn_12',
    userId: 'user_123',
    amount: 25.0,
    type: 'expense',
    category: 'Office Supplies',
    date: '2024-06-28T11:00:00Z',
    paymentMethod: 'Cash',
    description: 'Coffee for the team',
  },
  {
    id: 'txn_13',
    userId: 'user_123',
    amount: 150.0,
    type: 'expense',
    category: 'Utilities',
    date: '2024-06-30T12:00:00Z',
    paymentMethod: 'bKash',
    description: 'Electricity Bill',
  },
];

export const categories = [
  ...new Set(transactions.map((t) => t.category)),
  'Transfer',
];

export const paymentMethods = [
  ...new Set(transactions.map((t) => t.paymentMethod)),
  'bKash',
  'Cash',
];
